# Generated by Django 2.0.2 on 2019-04-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20190405_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
