# Generated by Django 2.0.2 on 2019-04-05 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='person.Person'),
        ),
    ]
